### ISSUE TITLE
Pinyin romanization doesn’t convert punctuation characters

### ISSUE THREAD

**Issue by jiru** [allan-simon/sinoparserd#13]
There is some code to [convert Chinese punctuation to Latin](https://github.com/allan-simon/sinoparserd/blob/fa634b22d649e6d9b65fec024ae14d5dfe50e3c5/src/Parser.h#L96-L105), but it’s not working because all the pairs contain multibyte characters as keys, while the input string is [segmented on bytes, not characters](https://github.com/allan-simon/sinoparserd/blob/fa634b22d649e6d9b65fec024ae14d5dfe50e3c5/src/Parser.h#L447). It’s not trivial to fix since C++ totally lacks UTF-8 support.

Reproduce with:
```sh
$ curl http://127.0.0.1:8042/pinyin?str=`php -r 'print urlencode("？。、");'`
<?xml version="1.0" encoding="UTF-8"?>
<root>
<romanization><![CDATA[？。、]]></romanization>
</root>
```
Expected: `<romanization><![CDATA[?.,]]></romanization>`

**Comment by allan-simon** [comment]
thanks to have caught the bug,  if I remember correctly though there's already a piece of code doing character splitting based on utf-8 , no ? (or was it in nihongparserd ?)

**Comment by jiru** [comment]
It was in nihongoparserd. It was a super simple parser I rolled.

So the different approaches may be go about resolving this issue could be:
* copying the nihongoparserd parser
* using a C++ utf8 library
* rewriting sinoparserd in another language like Python

What’s your preference?

**Comment by allan-simon** [comment]
i think the first one will fit, because you just need to be able to split, other would make sense only if we know we would still has a dozen of features to implement which would get advantages from either using a third party library or a completly different language
