### ISSUE TITLE
Source of `mandarin.xml` and `cantonese.xml`

### ISSUE THREAD

**Issue by Yorwba** [allan-simon/sinoparserd#16]
This came up in Tatoeba/tatoeba2#2189. There are a few pinyin errors in `mandarin.xml` that I currently plan to fix by using [CC-CEDICT](http://cc-cedict.org/) as the source instead, but maybe they have been corrected in the original source of `mandarin.xml` as well.

@allan-simon do you remember where you got those files from?

**Comment by allan-simon** [comment]
i think cc-cedict was the source for mandarin.xml 
and for cantonese.xml it was candodict

**Comment by Yorwba** [comment]
OK, thanks for the quick response. The latest export from CC-CEDICT has a lot fewer lines than `mandarin.xml`, so I thought you might have used another source. Seems like they decided that a lot of entries were unnecessary and deleted them.

**Comment by allan-simon** [comment]
or maybe i also combined it with the data file from adsotrans http://adsotrans.com/downloads/
